#include "stdafx.h"
#include "Music.h"

using namespace SoundManager;
using namespace SoundManager::Keys;

namespace Music
{

	Sequence happyFast =
	{
		{ INSTRUCTION_BALANCE, { 40, 70, 40, 100 }},
		{ INSTRUCTION_INSTRUMENT, { INSTRUMENT_SQUARE, INSTRUMENT_SQUARE, INSTRUMENT_SQUARE, INSTRUMENT_NOISE}},
		{ INSTRUCTION_TIMING, { 240, 8 } },
		{ INSTRUCTION_PLAY, { S|G  |3, S|G  |5, S|G  |5, Rest }},
		{ INSTRUCTION_TIMING, { 220, 8 } },
		{ INSTRUCTION_PLAY, { S|G  |3, S|G  |5, S|F  |5, Rest }},
		{ INSTRUCTION_TIMING, { 180, 8 } },
		{ INSTRUCTION_PLAY, { S|A  |3, S|G  |5, S|E  |5, Rest }},
		{ INSTRUCTION_TIMING, { 120, 8 } },
		{ INSTRUCTION_PLAY, { S|B  |3, S|G  |5, S|D  |5, Rest }},
		{ INSTRUCTION_TIMING, { 240, 16 } },
		{ INSTRUCTION_PLAY, {   C  |4,   A  |5,  Rest  , S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   A  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4, S|G  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   E  |4,  Rest  ,  Rest  , S| 1 }},
		{ INSTRUCTION_PLAY, { S|E  |4,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,   G  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|G  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   C  |4,   A  |5,  Rest  , S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   A  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|G  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   E  |4,   A  |5,  Rest  , S| 1 }},
		{ INSTRUCTION_PLAY, { S|E  |4,   A  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|G  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   D  |4, S|C  |6,  Rest  , S|20 }},
		{ INSTRUCTION_PLAY, { S|D  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|B  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   F  |4,   B  |5,  Rest  , S| 1 }},
		{ INSTRUCTION_PLAY, { S|F  |4, S|B  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   D  |4,  Rest  ,  Rest  , S|20 }},
		{ INSTRUCTION_PLAY, { S|D  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4,   G  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   F  |4,   G  |5,  Rest  , S| 1 }},
		{ INSTRUCTION_PLAY, { S|F  |4,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,   G  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  ,  Rest  ,    1 }},

		{ INSTRUCTION_PLAY, {   G  |3,   A  |5,  Rest  , S|20 }},
		{ INSTRUCTION_PLAY, { S|G  |3,   A  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4, S|G  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   B  |3,  Rest  ,  Rest  , S| 1 }},
		{ INSTRUCTION_PLAY, { S|B  |3,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,   G  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|G  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   D  |4,   A  |5,  Rest  , S|20 }},
		{ INSTRUCTION_PLAY, { S|D  |4,   A  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|G  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   B  |3,   A  |5,  Rest  , S| 1 }},
		{ INSTRUCTION_PLAY, { S|B  |3,   A  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|G  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   C  |4, S|D  |6,  Rest  , S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|C  |6,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   E  |4,   C  |6,  Rest  , S| 1 }},
		{ INSTRUCTION_PLAY, { S|E  |4, S|C  |6,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   C  |4,  Rest  ,  Rest  , S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4,   G  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   E  |4,   G  |5,  Rest  , S| 1 }},
		{ INSTRUCTION_PLAY, { S|E  |4,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,   G  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  ,  Rest  ,    1 }},

		{ INSTRUCTION_PLAY, {   E  |3,   G  |5,   G  |6, S|20 }},
		{ INSTRUCTION_PLAY, { S|E  |3,   G  |5,   G  |6,   20 }},
		{ INSTRUCTION_PLAY, {   C  |4,   G  |5,   G  |6,   20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   G  |5,   G  |6,   20 }},
		{ INSTRUCTION_PLAY, {   G  |3,   E  |5,   E  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|G  |3,   E  |5,   E  |6,    1 }},
		{ INSTRUCTION_PLAY, {   C  |4,   E  |5,   E  |6,    1 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   E  |5,   E  |6,    1 }},
		{ INSTRUCTION_PLAY, {   E  |3,   C  |5,   C  |6, S|20 }},
		{ INSTRUCTION_PLAY, { S|E  |3,   C  |5,   C  |6,   20 }},
		{ INSTRUCTION_PLAY, {   C  |4,   C  |5,   C  |6,   20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   C  |5,   C  |6,   20 }},
		{ INSTRUCTION_TIMING, { 240, 32 }},
		{ INSTRUCTION_PLAY, {   G  |3,   D  |5,   D  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|G  |3,   C  |5,   C  |6,    1 }},
		{ INSTRUCTION_PLAY, {   Rest ,   D  |5,   D  |6,    1 }},
		{ INSTRUCTION_PLAY, {   Rest ,   C  |5,   C  |6,    1 }},
		{ INSTRUCTION_PLAY, {   C  |4,   D  |5,   D  |6,    1 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   C  |5,   C  |6,    1 }},
		{ INSTRUCTION_PLAY, {   Rest ,   B  |4,   B  |5,    1 }},
		{ INSTRUCTION_PLAY, {   Rest ,   C  |5,   C  |6,    1 }},
		{ INSTRUCTION_TIMING, { 240, 8 }},
		{ INSTRUCTION_PLAY, { S|F  |3,   B  |4,   B  |5, S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   B  |4,   B  |5,   20 }},
		{ INSTRUCTION_PLAY, { S|A  |3,   B  |4,   B  |5, S| 1 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   B  |4,   B  |5,    1 }},
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |4, S|A  |5, S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   Rest ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, { S|A  |3, S|F  |5, S|F  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|C  |4, S|Dis|5, S|Dis|6,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |3, S|E  |5, S|E  |6, S|20 }},
		{ INSTRUCTION_PLAY, { S|E  |4, S|G  |5, S|G  |6,   20 }},
		{ INSTRUCTION_PLAY, { S|C  |4, S|E  |5, S|E  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|E  |4, S|C  |5, S|C  |6,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |3, S|D  |5, S|D  |6, S|20 }},
		{ INSTRUCTION_PLAY, { S|D  |4, S|F  |5, S|F  |6,   20 }},
		{ INSTRUCTION_PLAY, { S|B  |3, S|D  |5, S|D  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|D  |4, S|B  |4, S|B  |5,    1 }},
		{ INSTRUCTION_PLAY, { S|C  |3, S|C  |5, S|C  |6, S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,  Rest  , S|C  |6,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |3,  Rest  , S|B  |5, S| 1 }},
		{ INSTRUCTION_PLAY, { S|E  |3,  Rest  , S|A  |5,    1 }},

			// Repeat

		{ INSTRUCTION_TIMING, { 240, 8 } },
		{ INSTRUCTION_PLAY, { S|G  |3, S|G  |5, S|G  |5, Rest }},
		{ INSTRUCTION_TIMING, { 220, 8 } },
		{ INSTRUCTION_PLAY, { S|G  |3, S|G  |5, S|F  |5, Rest }},
		{ INSTRUCTION_TIMING, { 180, 8 } },
		{ INSTRUCTION_PLAY, { S|A  |3, S|G  |5, S|E  |5, Rest }},
		{ INSTRUCTION_TIMING, { 120, 8 } },
		{ INSTRUCTION_PLAY, { S|B  |3, S|G  |5, S|D  |5, Rest }},
		{ INSTRUCTION_TIMING, { 240, 16 } },
		{ INSTRUCTION_PLAY, {   C  |4,   A  |5, S|Fis|5, S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   A  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4, S|G  |5, S|G  |5,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   E  |4,  Rest  , S|G  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|E  |4,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,   G  |5, S|G  |5,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|G  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   C  |4,   A  |5, S|Fis|5, S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   A  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  , S|G  |5,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|G  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   E  |4,   A  |5, S|G  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|E  |4,   A  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  , S|G  |5,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|G  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   D  |4, S|C  |6, S|Fis|5, S|20 }},
		{ INSTRUCTION_PLAY, { S|D  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  , S|G  |5,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|B  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   F  |4,   B  |5, S|G  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|F  |4, S|B  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  , S|G  |5,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   D  |4,  Rest  , S|G  |3, S|20 }},
		{ INSTRUCTION_PLAY, { S|D  |4,  Rest  , S|Gis|3,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4,   G  |5, S|A  |3,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  , S|Ais|3,   20 }},
		{ INSTRUCTION_PLAY, {   F  |4,   G  |5, S|B  |3, S| 1 }},
		{ INSTRUCTION_PLAY, { S|F  |4,  Rest  , S|Ais|3,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,   G  |5, S|A  |3,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  , S|Gis|3,    1 }},

		{ INSTRUCTION_PLAY, {   G  |3,   A  |5, S|G  |3, S|20 }},
		{ INSTRUCTION_PLAY, { S|G  |3,   A  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4, S|G  |5, S|G  |5,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   B  |3,  Rest  , S|G  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|B  |3,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,   G  |5, S|G  |5,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|G  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   D  |4,   A  |5, S|Fis|5, S|20 }},
		{ INSTRUCTION_PLAY, { S|D  |4,   A  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  , S|G  |5,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|G  |5,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   B  |3,   A  |5, S|G  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|B  |3,   A  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  , S|G  |5,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|G  |5,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   C  |4, S|D  |6, S|Fis|5, S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,  Rest  ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  , S|G  |5,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4, S|C  |6,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, {   E  |4,   C  |6, S|G  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|E  |4, S|C  |6,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,  Rest  , S|G  |5,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {   C  |4,  Rest  , S|G  |3, S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,  Rest  , S|Gis|3,   20 }},
		{ INSTRUCTION_PLAY, {   G  |4,   G  |5, S|A  |3,   20 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  , S|Ais|3,   20 }},
		{ INSTRUCTION_PLAY, {   E  |4,   G  |5, S|B  |3, S| 1 }},
		{ INSTRUCTION_PLAY, { S|E  |4,  Rest  , S|Ais|3,    1 }},
		{ INSTRUCTION_PLAY, {   G  |4,   G  |5, S|A  |3,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |4,  Rest  , S|Gis|3,    1 }},

		{ INSTRUCTION_PLAY, {   E  |3,   G  |5,   G  |6, S|20 }},
		{ INSTRUCTION_PLAY, { S|E  |3,   G  |5,   G  |6,   20 }},
		{ INSTRUCTION_PLAY, {   C  |4,   G  |5,   G  |6,   20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   G  |5,   G  |6,   20 }},
		{ INSTRUCTION_PLAY, {   G  |3,   E  |5,   E  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|G  |3,   E  |5,   E  |6,    1 }},
		{ INSTRUCTION_PLAY, {   C  |4,   E  |5,   E  |6,    1 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   E  |5,   E  |6,    1 }},
		{ INSTRUCTION_PLAY, {   E  |3,   C  |5,   C  |6, S|20 }},
		{ INSTRUCTION_PLAY, { S|E  |3,   C  |5,   C  |6,   20 }},
		{ INSTRUCTION_PLAY, {   C  |4,   C  |5,   C  |6,   20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   C  |5,   C  |6,   20 }},
		{ INSTRUCTION_TIMING, { 240, 32 }},
		{ INSTRUCTION_PLAY, {   G  |3,   D  |5,   D  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|G  |3,   C  |5,   C  |6,    1 }},
		{ INSTRUCTION_PLAY, {   Rest ,   D  |5,   D  |6,    1 }},
		{ INSTRUCTION_PLAY, {   Rest ,   C  |5,   C  |6,    1 }},
		{ INSTRUCTION_PLAY, {   C  |4,   D  |5,   D  |6,    1 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   C  |5,   C  |6,    1 }},
		{ INSTRUCTION_PLAY, {   Rest ,   B  |4,   B  |5,    1 }},
		{ INSTRUCTION_PLAY, {   Rest ,   C  |5,   C  |6,    1 }},
		{ INSTRUCTION_TIMING, { 240, 8 }},
		{ INSTRUCTION_PLAY, { S|F  |3,   B  |4,   B  |5, S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   B  |4,   B  |5,   20 }},
		{ INSTRUCTION_PLAY, { S|A  |3,   B  |4,   B  |5, S| 1 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   B  |4,   B  |5,    1 }},
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |4, S|A  |5, S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4,   Rest ,  Rest  ,   20 }},
		{ INSTRUCTION_PLAY, { S|A  |3, S|F  |5, S|F  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|C  |4, S|Dis|5, S|Dis|6,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |3, S|E  |5, S|E  |6, S|20 }},
		{ INSTRUCTION_PLAY, { S|E  |4, S|G  |5, S|G  |6,   20 }},
		{ INSTRUCTION_PLAY, { S|C  |4, S|E  |5, S|E  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|E  |4, S|C  |5, S|C  |6,    1 }},
		{ INSTRUCTION_PLAY, { S|G  |3, S|D  |5, S|D  |6, S|20 }},
		{ INSTRUCTION_PLAY, { S|D  |4, S|F  |5, S|F  |6,   20 }},
		{ INSTRUCTION_PLAY, { S|B  |3, S|D  |5, S|D  |6, S| 1 }},
		{ INSTRUCTION_PLAY, { S|D  |4, S|B  |4, S|B  |5,    1 }},
		{ INSTRUCTION_TIMING, { 180, 8 }},
		{ INSTRUCTION_PLAY, { S|C  |3,   C  |5,   C  |6, S|20 }},
		{ INSTRUCTION_PLAY, { S|C  |4, S|C  |5, S|C  |6,   20 }},
		{ INSTRUCTION_TIMING, { 120, 8 }},
		{ INSTRUCTION_PLAY, { S|G  |3, S|E  |5, S|C  |5, S| 1 }},
		{ INSTRUCTION_PLAY, { S|E  |3,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_TIMING, { 60, 8 }},
		{ INSTRUCTION_PLAY, {   C  |3,   C  |5,   C  |5, S| 1 }},
		{ INSTRUCTION_PLAY, {   C  |3,   C  |5,   C  |5,    1 }},
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  ,    1 }},
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  ,    1 }},
	};

}
