#include "stdafx.h"
#include "Music.h"

using namespace SoundManager;
using namespace SoundManager::Keys;

namespace Music
{

	Sequence toccata =
	{
		{ INSTRUCTION_TIMING, { 148, 16 } },
		{ INSTRUCTION_INSTRUMENT, { INSTRUMENT_SQUARE, INSTRUMENT_SQUARE, INSTRUMENT_SQUARE, INSTRUMENT_SQUARE } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, F  |5 } },
		{ INSTRUCTION_TIMING, { 156, 16 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, E  |5 } },
		{ INSTRUCTION_TIMING, { 164, 16 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, F  |5 } },
		{ INSTRUCTION_TIMING, { 172, 16 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },
		{ INSTRUCTION_TIMING, { 180, 16 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , A  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , F  |4 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, A  |4 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },

		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, E  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, D  |5 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, E  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , A  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , F  |4 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, A  |4 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },

		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, D  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, D  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , A  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , F  |4 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, A  |4 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },

		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, E  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, D  |5 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, E  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , A  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , F  |4 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, A  |4 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },

		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, F  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, E  |5 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, F  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , A  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , F  |4 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, A  |4 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },

		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, E  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, D  |5 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, E  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , A  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , F  |4 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, A  |4 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },

		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, D  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, D  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , A  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , F  |4 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   C  |4, A  |4 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|C  |4, C  |5 } },

		{ INSTRUCTION_PLAY, {   G  |3,   B  |3,   E  |4, E  |5 } },
		{ INSTRUCTION_PLAY, { S|G  |3, S|B  |3, S|E  |4, B  |4 } },
		{ INSTRUCTION_PLAY, {   G  |3,   B  |3,   E  |4, E  |5 } },
		{ INSTRUCTION_PLAY, { S|G  |3, S|B  |3, S|E  |4, B  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , F  |4 } },
		{ INSTRUCTION_PLAY, {   G  |3,   B  |3,   E  |4, G  |4 } },
		{ INSTRUCTION_PLAY, { S|G  |3, S|B  |3, S|E  |4, B  |4 } },

		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, C  |5 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, B  |4 } },
		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, C  |5 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , E  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , C  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, E  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },

		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, A  |4 } },
		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , E  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , C  |4 } },
		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, E  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },

		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, A  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },
		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, A  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , E  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , C  |4 } },
		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, E  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },

		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, A  |4 } },
		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , E  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , C  |4 } },
		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, E  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },

		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, C  |5 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, B  |4 } },
		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, C  |5 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , E  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , C  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, E  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },

		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, A  |4 } },
		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , E  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , C  |4 } },
		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, E  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },

		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, A  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },
		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, A  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , E  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , C  |4 } },
		{ INSTRUCTION_PLAY, {   C  |3,   E  |3,   G  |3, E  |4 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|E  |3, S|G  |3, G  |4 } },

		{ INSTRUCTION_PLAY, {   D  |3,   Fis|3,   B  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|Fis|3, S|B  |3, Fis|4 } },
		{ INSTRUCTION_PLAY, {   D  |3,   Fis|3,   B  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|Fis|3, S|B  |3, Fis|4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , D  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , C  |4 } },
		{ INSTRUCTION_PLAY, {   D  |3,   Fis|3,   B  |3, D  |4 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|Fis|3, S|B  |3, Fis|4 } },

		{ INSTRUCTION_PLAY, {   G  |2,   B  |2,   D  |3, G  |4 } },
		{ INSTRUCTION_PLAY, { S|G  |2, S|B  |2, S|D  |3, Fis|4 } },
		{ INSTRUCTION_PLAY, {   G  |2,   B  |2,   D  |3, G  |4 } },
		{ INSTRUCTION_PLAY, { S|G  |2, S|B  |2, S|D  |3, D  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , B  |3 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , G  |3 } },
		{ INSTRUCTION_PLAY, { S|G  |2, S|B  |2, S|D  |3, B  |3 } },
		{ INSTRUCTION_PLAY, { S|G  |2, S|B  |2, S|D  |3, D  |4 } },

		{ INSTRUCTION_PLAY, {   Cis|3,   E  |3,   G  |3, A  |4 } },
		{ INSTRUCTION_PLAY, { S|Cis|3, S|E  |3, S|G  |3, Gis|4 } },
		{ INSTRUCTION_PLAY, {   Cis|3,   E  |3,   G  |3, A  |4 } },
		{ INSTRUCTION_PLAY, { S|Cis|3, S|E  |3, S|G  |3, E  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , Cis|4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , A  |3 } },
		{ INSTRUCTION_PLAY, {   Cis|3,   E  |3,   G  |3, Cis|4 } },
		{ INSTRUCTION_PLAY, { S|Cis|3, S|E  |3, S|G  |3, E  |4 } },

		{ INSTRUCTION_PLAY, {   D  |3,   F  |3,   G  |3, A  |4 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|F  |3, S|G  |3, F  |4 } },
		{ INSTRUCTION_PLAY, {   D  |3,   F  |3,   G  |3, A  |4 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|F  |3, S|G  |3, F  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , D  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , A  |3 } },
		{ INSTRUCTION_PLAY, {   D  |3,   F  |3,   G  |3, D  |4 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|F  |3, S|G  |3, F  |4 } },

		{ INSTRUCTION_PLAY, {   Cis|3,   E  |3,   G  |3, A  |4 } },
		{ INSTRUCTION_PLAY, { S|Cis|3, S|E  |3, S|G  |3, Gis|4 } },
		{ INSTRUCTION_PLAY, {   Cis|3,   E  |3,   G  |3, A  |4 } },
		{ INSTRUCTION_PLAY, { S|Cis|3, S|E  |3, S|G  |3, E  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , Cis|4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , A  |3 } },
		{ INSTRUCTION_PLAY, {   Cis|3,   E  |3,   G  |3, Cis|4 } },
		{ INSTRUCTION_PLAY, { S|Cis|3, S|E  |3, S|G  |3, E  |4 } },

		{ INSTRUCTION_PLAY, {   D  |3,   F  |3,   G  |2, A  |4 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|F  |3, S|G  |2, F  |4 } },
		{ INSTRUCTION_PLAY, {   D  |3,   F  |3,   G  |2, A  |4 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|F  |3, S|G  |2, F  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , D  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , A  |3 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|F  |3,  Rest  , D  |4 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|F  |3,  Rest  , F  |4 } },

		{ INSTRUCTION_PLAY, {   Dis|3,   Fis|3,   A  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|Dis|3, S|Fis|3, S|A  |3, Ais|4 } },
		{ INSTRUCTION_PLAY, {   Dis|3,   Fis|3,   A  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|Dis|3, S|Fis|3, S|A  |3, Fis|4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , Dis|4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , B  |3 } },
		{ INSTRUCTION_PLAY, {   Dis|3,   Fis|3,   A  |3, Dis|4 } },
		{ INSTRUCTION_PLAY, { S|Dis|3, S|Fis|3, S|A  |3, Fis|4 } },

		{ INSTRUCTION_PLAY, {   E  |3,   G  |3,   A  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3, S|A  |3, G  |4 } },
		{ INSTRUCTION_PLAY, {   E  |3,   G  |3,   A  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3, S|A  |3, G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , E  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , B  |3 } },
		{ INSTRUCTION_PLAY, {   E  |3,   G  |3,   A  |3, E  |4 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3, S|A  |3, G  |4 } },

		{ INSTRUCTION_PLAY, {   Dis|3,   Fis|3,   A  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|Dis|3, S|Fis|3, S|A  |3, Ais|4 } },
		{ INSTRUCTION_PLAY, {   Dis|3,   Fis|3,   A  |3, B  |4 } },
		{ INSTRUCTION_PLAY, { S|Dis|3, S|Fis|3, S|A  |3, Fis|4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , Dis|4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , B  |3 } },
		{ INSTRUCTION_PLAY, {   Dis|3,   Fis|3,   A  |3, Dis|4 } },
		{ INSTRUCTION_PLAY, { S|Dis|3, S|Fis|3, S|A  |3, Fis|4 } },

		{ INSTRUCTION_PLAY, {   E  |3,   G  |3,   G  |2, B  |4 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3, S|G  |2, G  |4 } },
		{ INSTRUCTION_PLAY, {   E  |3,   G  |3,   G  |2, B  |4 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3, S|G  |2, G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , E  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , B  |3 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3,  Rest  , E  |4 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3,  Rest  , G  |4 } },

		{ INSTRUCTION_PLAY, {   E  |3,   G  |3,   Bes|3, C  |5 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3, S|Bes|3, B  |4 } },
		{ INSTRUCTION_PLAY, {   E  |3,   G  |3,   Bes|3, C  |5 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3, S|Bes|3, G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , E  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , C  |4 } },
		{ INSTRUCTION_PLAY, {   E  |3,   G  |3,   Bes|3, E  |4 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3, S|Bes|3, G  |4 } },

		{ INSTRUCTION_PLAY, {   D  |3,   F  |3,   Bes|3, C  |5 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|F  |3, S|Bes|3, F  |4 } },
		{ INSTRUCTION_PLAY, {   D  |3,   F  |3,   Bes|3, C  |5 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|F  |3, S|Bes|3, F  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , D  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , C  |4 } },
		{ INSTRUCTION_PLAY, {   D  |3,   F  |3,   Bes|3, D  |4 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|F  |3, S|Bes|3, F  |4 } },

		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   Bes|3, C  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|Bes|3, A  |4 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   Bes|3, C  |5 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|Bes|3, A  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , F  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , C  |4 } },
		{ INSTRUCTION_PLAY, {   F  |3,   A  |3,   Bes|3, F  |4 } },
		{ INSTRUCTION_PLAY, { S|F  |3, S|A  |3, S|Bes|3, A  |4 } },

		{ INSTRUCTION_PLAY, {   E  |3,   G  |3,   Bes|3, C  |5 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3, S|Bes|3, G  |4 } },
		{ INSTRUCTION_PLAY, {   E  |3,   G  |3,   Bes|3, C  |5 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3, S|Bes|3, G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , E  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , C  |4 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3, S|Bes|3, E  |4 } },
		{ INSTRUCTION_PLAY, { S|E  |3, S|G  |3, S|Bes|3, A  |4 } },

		{ INSTRUCTION_PLAY, {   Es |3,   G  |3,   Bes|3, Cis|5 } },
		{ INSTRUCTION_PLAY, { S|Es |3, S|G  |3, S|Bes|3, Bes|4 } },
		{ INSTRUCTION_PLAY, {   Es |3,   G  |3,   Bes|3, Cis|5 } },
		{ INSTRUCTION_PLAY, { S|Es |3, S|G  |3, S|Bes|3, Bes|4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , Cis|4 } },
		{ INSTRUCTION_PLAY, {   Es |3,   G  |3,   Bes|3, G  |4 } },
		{ INSTRUCTION_PLAY, { S|Es |3, S|G  |3, S|Bes|3, Bes|4 } },

		{ INSTRUCTION_PLAY, {   D  |3,   G  |3,   Bes|3, D  |5 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|G  |3, S|Bes|3, Cis|5 } },
		{ INSTRUCTION_PLAY, {   D  |3,   G  |3,   Bes|3, D  |5 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|G  |3, S|Bes|3, Bes|4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , G  |4 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , D  |4 } },
		{ INSTRUCTION_TIMING, { 180, 16 } },
		{ INSTRUCTION_PLAY, {   D  |3,   G  |3,   Bes|3, G  |4 } },
		{ INSTRUCTION_TIMING, { 175, 16 } },
		{ INSTRUCTION_PLAY, { S|D  |3, S|G  |3, S|Bes|3, Bes|4 } },

		{ INSTRUCTION_TIMING, { 170, 16 } },
		{ INSTRUCTION_PLAY, {   C  |3,   G  |3,   Bes|3, E  |5 } },
		{ INSTRUCTION_TIMING, { 165, 16 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|G  |3, S|Bes|3, Dis|5 } },
		{ INSTRUCTION_TIMING, { 160, 16 } },
		{ INSTRUCTION_PLAY, {   C  |3,   G  |3,   Bes|3, E  |5 } },
		{ INSTRUCTION_TIMING, { 155, 16 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|G  |3, S|Bes|3, C  |5 } },
		{ INSTRUCTION_TIMING, { 150, 16 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , Bes|4 } },
		{ INSTRUCTION_TIMING, { 145, 16 } },
		{ INSTRUCTION_PLAY, {  Rest  ,  Rest  ,  Rest  , G  |4 } },
		{ INSTRUCTION_TIMING, { 140, 16 } },
		{ INSTRUCTION_PLAY, {   C  |3,   G  |3,   Bes|3, Bes|4 } },
		{ INSTRUCTION_TIMING, { 70, 16 } },
		{ INSTRUCTION_PLAY, { S|C  |3, S|G  |3, S|Bes|3, E  |5 } },
	};
}
